// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM9l5uLB78KK573UMqHct4URvod2IgWQo',
    appId: '1:304052902507:web:f4571ce13e8caa6ce2ef2e',
    messagingSenderId: '304052902507',
    projectId: 'instagram-clone-7be79',
    authDomain: 'instagram-clone-7be79.firebaseapp.com',
    storageBucket: 'instagram-clone-7be79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm6SIpsfUDtcBWRHIamCsBBy9zgNz70nw',
    appId: '1:304052902507:android:270ebabba17f3512e2ef2e',
    messagingSenderId: '304052902507',
    projectId: 'instagram-clone-7be79',
    storageBucket: 'instagram-clone-7be79.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM9l5uLB78KK573UMqHct4URvod2IgWQo',
    appId: '1:304052902507:web:f34efb115c3e8b7ce2ef2e',
    messagingSenderId: '304052902507',
    projectId: 'instagram-clone-7be79',
    authDomain: 'instagram-clone-7be79.firebaseapp.com',
    storageBucket: 'instagram-clone-7be79.firebasestorage.app',
  );
}
